<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE activityList[
<!ELEMENT activityList (activity+)>
<!ELEMENT activity ( name, category?, description?, intensityLevel?, maxPeopleAllowed?, requirementOne?, requirementTwo?, price?, durationMinutes)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT intensityLevel (#PCDATA)>
<!ELEMENT maxPeopleAllowed (#PCDATA)>
<!ELEMENT requirementOne (#PCDATA)>
<!ELEMENT requirementTwo (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT durationMinutes (#PCDATA)>
]>
<activityList>
  <activity>
    <name>Cardio Blitz</name>
    <category>Aerobic</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Super Circuit</name>
    <category>Aerobic &amp; Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Strength and Conditioning Circuit</name>
    <category>Aerobic &amp; Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Boxing Circuit</name>
    <category>Aerobic &amp; Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo>BYO boxing gloves, wraps and inner liners.</requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Stength</name>
    <category>Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Very High</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Mobility Fit</name>
    <category>Flexibility</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo>BYO mat</requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Tabata</name>
    <category>Aerobic</category>
    <description>Lorem ipsum</description>
    <intensityLevel>High</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>Restorative Stretch</name>
    <category>Flexibility</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Low</intensityLevel>
    <maxPeopleAllowed>26</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo>BYO mat</requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>TRX HIIT</name>
    <category>Aerobic &amp; Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>High</intensityLevel>
    <maxPeopleAllowed>14</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
  <activity>
    <name>TRX</name>
    <category>Strength</category>
    <description>Lorem ipsum</description>
    <intensityLevel>Medium</intensityLevel>
    <maxPeopleAllowed>14</maxPeopleAllowed>
    <requirementOne>Large towels are compulsory for Group Exercise and Gym.</requirementOne>
    <requirementTwo></requirementTwo>
    <price>60</price>
    <durationMinutes>45</durationMinutes>
  </activity>
</activityList>